# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justin's TechBlog
email: justinbarias@live.com
description: > # this means to ignore newlines until "baseurl:"
  A Software engineer with a tangent on DevOps/SRE and all things cloud - from the dark world of WinTel. Loves to play around with CI/CD tools, and all things cloud scale, and spends much of his time gaming. 
  If you're a Ops/Infra/WinTel guy looking to transform into something more relevant, this is your blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.jbdevops.com" # the base hostname & protocol for your site
github_username:  justinbarias
# Google services
google_analytics: 'UA-77974211-1'
# Build settings
markdown: kramdown
comments: true

